[package]
name = "eventsourcingdb-es"
version = "0.1.0"
authors = ["daniel-mader"]
description = "An EventSourcingDB implementation of the cqrs-es event store."
edition = "2024"
repository = "https://github.com/impierce/eventsourcingdb-es"
license = "Apache-2.0"
keywords = ["cqrs", "event-sourcing", "eventsourcingdb", "cqrs-es"]

[dependencies]
async-trait = "0.1"
cqrs-es = "0.4.12"
eventsourcingdb = "1.1.0"
futures = "0.3"
regex = "1.12"
serde_json = "1.0"
tokio = { version = "1.49" }
url = "2.5"

[dev-dependencies]
rand = "0.9"
