name: Coverage

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest

    services:
      eventsourcingdb:
        image: thenativeweb/eventsourcingdb
        options: >-
          run
          --api-token=secret
          --data-directory-temporary
          --http-enabled
          --https-enabled=false

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Generate code coverage
        run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
